const fs = require('fs');
const content = fs.readFileSync('src/data/roadguideStagesPart3.ts', 'utf-8');

const newStages = `
  // =========================================================================
  // STAGE 31 (Parte 31) - Cavaleiro Artorias e Invasores Malditos
  // =========================================================================
  {
    id: 'stage-31',
    number: 31,
    title: 'Estágio 31: Cavaleiro Artorias e Invasores Malditos',
    subtitle: 'Derrotando Artorias, Ciaran, Magias do Abismo e Invasões no Município',
    zone: 'Arena de Artorias & Oolacile Township',
    recommendedDex: '40 DEX',
    recommendedPyroFlame: 'Great Combustion (Cast rápido)',
    summary: 'Enfrentamento direto com o lendário Cavaleiro Artorias the Abysswalker focando em quebrar seu buff de Miasma. Encontro com a Lord\\'s Blade Ciaran para obter as adagas Dark Silver Tracer e Gold Tracer (ou matá-la pelo set). Descida ao Oolacile Township, enfrentando Bloatheads, Dark Sorcerers e o fantasma invasor de Marvelous Chester. Coleta de magias vitais como Dark Orb e a relíquia defensiva Silver Pendant.',
    keyRewards: [
      'Soul of Artorias',
      'Dark Silver Tracer & Gold Tracer (Troca ou Morte de Ciaran)',
      'Lord\\'s Blade Armor Set (Se matar Ciaran)',
      'Silver Pendant (Atalho de luz iluminada)',
      'Feitiço Sombrio Dark Orb',
      'Carvings (I\\'m Sorry, Hello)',
    ],
    levelRange: 'Lv. 84',
    buildStatus: {
      startLevel: 'Level 84',
      endLevel: 'Level 84',
      weapons: 'Balder Side Sword +15 / Gold Tracer',
      focusStat: 'Vitalidade 30, Endurance 31, Destreza 40',
      defense: 'Grass Crest Shield (Costas) + Dark Wood Grain Ring',
    },
    combatTactics: [
      {
        name: 'Quebrando o Buff do Abismo',
        description: 'Quando Artorias recuar para reunir miasma roxo, corra até ele sem hesitar e ataque freneticamente com a arma em duas mãos para quebrar a guarda e cancelar o dano fatal.',
        tag: 'Boss Strat',
      },
      {
        name: 'Esquiva Rápida (Fast Roll)',
        description: 'O Dark Wood Grain Ring permite rolar com mais quadros de invencibilidade sob os saltos agressivos de Artorias.',
        tag: 'Survival Tech',
      },
      {
        name: 'Invasor Marvelous Chester',
        description: 'Lute usando desníveis contra Chester; abuse de parries ou encurte a distância de forma super agressiva para evitar sangramentos das facas dele.',
        tag: 'PvP Strat',
      },
    ],
    guideSections: [
      {
        id: 'sec-31-1',
        title: '1. O Abysswalker',
        badge: 'Artorias',
        items: [
          'Preparo: Escudo leve (Grass Crest) nas costas, anel do ninja, arma buffada com resina.',
          'Combate: Puna os saltos esquivando para o lado e limite a gula a 2 ataques.',
          'Quebra de Guarda: Impessa o buff de Miasma com ataques rápidos a duas mãos.',
        ],
      },
      {
        id: 'sec-31-2',
        title: '2. O Túmulo e Ciaran',
        badge: 'Ciaran',
        items: [
          'Agachada na Arena: Fale com Lord\\'s Blade Ciaran no centro da arena de Artorias após recarregar a área.',
          'Decisão: Entregue a Alma de Artorias para pegar as adagas, ou derrote a NPC para pegar o Set de armadura e as armas.',
        ],
      },
      {
        id: 'sec-31-3',
        title: '3. O Município e o Silver Pendant',
        badge: 'Oolacile Township',
        items: [
          'Fogueira Central: Avance pelas escadas atrás da arena.',
          'Iluminar Passagem Secreta: Use uma fonte de luz numa parede suspeita nos andares intermediários para obter o Silver Pendant.',
          'Invasões e Chester: Defenda-se do fantasma Marvelous Chester próximo aos magos.',
          'Coletar Feitiços e Atalho: Colete o Dark Orb e ative o elevador de atalho de madeira para o térreo.',
        ],
      },
    ],
    tasks: [
      {
        id: 'task-31-1',
        stageId: 'stage-31',
        title: 'Derrotar o Cavaleiro Artorias (Artorias the Abysswalker)',
        description: 'Quebre os buffs de miasma para vencer a luta épica na Royal Wood.',
        category: 'boss',
        priority: 'essential',
        location: 'Arena de Artorias (Coliseu)',
        completed: false,
      },
      {
        id: 'task-31-2',
        stageId: 'stage-31',
        title: 'Conseguir a Dark Silver Tracer e Gold Tracer',
        description: 'Fale com Ciaran ou derrote-a para obter as lâminas lendárias de destreza.',
        category: 'weapon',
        priority: 'essential',
        location: 'Arena de Artorias (após matar o chefe)',
        completed: false,
      },
      {
        id: 'task-31-3',
        stageId: 'stage-31',
        title: 'Revelar a parede secreta e pegar o Silver Pendant',
        description: 'Use a Cast Light ou Skull Lantern para acessar a relíquia que desvia magias negras.',
        category: 'item',
        priority: 'essential',
        location: 'Oolacile Township',
        completed: false,
      },
      {
        id: 'task-31-4',
        stageId: 'stage-31',
        title: 'Derrotar a invasão do fantasma Marvelous Chester',
        description: 'Vença Chester na ponte estreita para avançar na quest dele.',
        category: 'npc',
        priority: 'recommended',
        location: 'Oolacile Township',
        completed: false,
      },
      {
        id: 'task-31-5',
        stageId: 'stage-31',
        title: 'Coletar o feitiço sombrio Dark Orb e ativar o atalho do elevador',
        description: 'Avance até o térreo do município e pegue as magias nos telhados e sacadas.',
        category: 'exploration',
        priority: 'essential',
        location: 'Oolacile Township (Térreo)',
        completed: false,
      },
    ],
  },

  // =========================================================================
  // STAGE 32 (Parte 32) - Manus, Pai do Abismo
  // =========================================================================
  {
    id: 'stage-32',
    number: 32,
    title: 'Estágio 32: Manus, Pai do Abismo',
    subtitle: 'Oolacile Dungeon, Resgate do Sif, Piromancia Negra e Fim da Linha',
    zone: 'Oolacile Dungeon & Chasm of the Abyss',
    recommendedDex: '40 DEX',
    recommendedPyroFlame: 'Black Flame & Silver Pendant (Acesso Rápido)',
    summary: 'Avanço cuidadoso pela Oolacile Dungeon desviando de feitiços Dark Bead mortais, chegando na escuridão do Chasm of the Abyss para farmar humanidades fantasmas. Descoberta da parede ilusória guiada por Alvina para resgatar o Great Grey Wolf Sif e obter o Cleansing Greatshield. Coleta da formidável piromancia Black Flame e White Titanite Slab. O apogeu da DLC: Derrotar Manus, Pai do Abismo usando o Silver Pendant e auxílio de Sif, garantindo a salvação final de Dusk.',
    keyRewards: [
      'Cleansing Greatshield (Protegendo Sif)',
      'Black Flame (Piromancia do Abismo)',
      'White Titanite Slab',
      'Soul of Manus',
      '10 Humanidades Sólidas (Drops do Abismo)',
      'Resgate da Dusk of Oolacile (Nova interação)',
    ],
    levelRange: 'Lv. 91',
    buildStatus: {
      startLevel: 'Level 91',
      endLevel: 'Level 91',
      weapons: 'Uchigatana / Furysword + Escudo de Cristal (Maior defesa mágica do set)',
      focusStat: 'Conhecimento 23, Força 16, Resistência 17',
      defense: 'Gold-Hemmed Black Set + Bellowing Dragoncrest Ring',
    },
    combatTactics: [
      {
        name: 'Defesa Mágica & Silver Pendant',
        description: 'Toda vez que Manus invocar magias do Abismo em chuva ou círculo convergente, faça SPAM (uso contínuo) do Silver Pendant para repelir a magia.',
        tag: 'Boss Strat',
      },
      {
        name: 'Punir o Braço de Manus',
        description: 'Somente ataque Manus quando ele executar um soco forte vertical e a grande mão dele ficar presa ao chão por 2-3 segundos.',
        tag: 'Combat Tech',
      },
      {
        name: 'Farm de Humanidade Fantasma',
        description: 'Os sprites (fantasminhas escuros) da fenda do abismo possuem uma enorme taxa de queda para Twin Humanities e Humanities soltas. Excelente lugar para farm.',
        tag: 'Farming Strat',
      },
    ],
    guideSections: [
      {
        id: 'sec-32-1',
        title: '1. Masmorra de Oolacile',
        badge: 'Dark Bead',
        items: [
          'Evite o Fogo Cruzado: Dark Sorcerers aplicam grande dano. Use pilares como cobertura.',
          'Fogueira Inferior: Atravesse a ponte suspensa até a fogueira do Chasm of the Abyss.',
        ],
      },
      {
        id: 'sec-32-2',
        title: '2. O Resgate de Sif e Itens Críticos',
        badge: 'Sif & Black Flame',
        items: [
          'Alvina Guia: Siga a gatinha fantasma até a última aparição, bata na parede ilusória e desça para defender Sif dos espíritos de humanidade e pegue o Cleansing Greatshield.',
          'Loots do Abismo: Navegue pelas beiradas escuras para coletar a Black Flame, White Titanite Slab e Carving.',
        ],
      },
      {
        id: 'sec-32-3',
        title: '3. A Luta Final do Abismo',
        badge: 'Manus',
        items: [
          'Invocação de Sif: O sinal dele aparece DENTRO da arena. Assim que cair, procure o sinal no chão se precisar de ajuda com aggro.',
          'Defensiva e Punição: Mantenha a guarda com escudo de alto poise. Desvie para trás. Ataque a mão quando estiver no chão.',
          'Finalização: Resgate Dusk of Oolacile (caída na arena) sem atacá-la e acenda a fogueira da vitória.',
        ],
      },
    ],
    tasks: [
      {
        id: 'task-32-1',
        stageId: 'stage-32',
        title: 'Navegar Oolacile Dungeon e descer ao Chasm of the Abyss',
        description: 'Sobreviva aos feiticeiros e acenda a última fogueira do abismo.',
        category: 'exploration',
        priority: 'essential',
        location: 'Oolacile Dungeon',
        completed: false,
      },
      {
        id: 'task-32-2',
        stageId: 'stage-32',
        title: 'Seguir Alvina, quebrar a parede ilusória e salvar o Lobo Sif',
        description: 'Derrote a humanidade hostil ao redor da barreira e obtenha o Cleansing Greatshield.',
        category: 'npc',
        priority: 'essential',
        location: 'Chasm of the Abyss',
        completed: false,
      },
      {
        id: 'task-32-3',
        stageId: 'stage-32',
        title: 'Coletar a Black Flame e a White Titanite Slab',
        description: 'Explore meticulosamente a escuridão do abismo antes do chefe.',
        category: 'item',
        priority: 'essential',
        location: 'Chasm of the Abyss',
        completed: false,
      },
      {
        id: 'task-32-4',
        stageId: 'stage-32',
        title: '⭐ Derrotar Manus, Pai do Abismo',
        description: 'Utilize o Silver Pendant para rechaçar as magias e derrote a fonte corrupta do abismo.',
        category: 'boss',
        priority: 'essential',
        location: 'Arena de Manus',
        completed: false,
      },
      {
        id: 'task-32-5',
        stageId: 'stage-32',
        title: 'Confirmar resgate pacífico de Dusk of Oolacile',
        description: 'Observe Dusk caída e suspirando na arena pós-boss; não ataque.',
        category: 'npc',
        priority: 'essential',
        location: 'Arena de Manus',
        completed: false,
      },
    ],
  },

  // =========================================================================
  // STAGE 33 (Parte 33) - Desafio 2 Cachorros e Black Dragon Kalameet
  // =========================================================================
  {
    id: 'stage-33',
    number: 33,
    title: 'Estágio 33: O Dragão Negro Kalameet e a Batalha Dupla',
    subtitle: 'Gough, O Pássaro Gigante Abatido e o Corte de Rabo mais Difícil do Jogo',
    zone: 'Sanctuary Garden, Torre de Gough & Vale de Kalameet',
    recommendedDex: '40 DEX',
    recommendedPyroFlame: 'Kindle para 20 Estus (Preparação Exaustiva)',
    summary: 'Episódio focado nos chefes opcionais supremos da DLC. Retorno ao Sanctuary Garden para o desafio esmagador de enfrentar dois Sanctuary Guardians de uma só vez (os "dois cachorros"). Subida à torre destrancada com a Crest Key para encontrar Hawkeye Gough e pedir para ele abater o dragão Kalameet com um tiro genial. Descida ao vale para enfrentar o Black Dragon de igual para igual, extraindo a raríssima Obsidian Greatsword pelo corte da cauda e garantindo o infame Calamity Ring.',
    keyRewards: [
      'Obsidian Greatsword (Corte da cauda de Kalameet)',
      'Calamity Ring (Derrotando Kalameet)',
      'Titanite Slab (Na arena de Kalameet)',
      'A cena épica de Hawkeye Gough atirando no dragão',
      'Desafio Pessoal (Vitória contra os 2 Guardiões Duplos)',
    ],
    levelRange: 'Lv. 94',
    buildStatus: {
      startLevel: 'Level 92',
      endLevel: 'Level 94',
      weapons: 'Uchigatana (Para alcance vertical no rabo)',
      focusStat: 'Resistência elevada para 20, Endurance 30',
      defense: 'Black Knight Shield (95% Resist. Fogo) + Gold-Hemmed Black Set',
    },
    combatTactics: [
      {
        name: 'Dividir e Conquistar os 2 Guardiões',
        description: 'Ambos atacam incansavelmente. Defenda sem parar e busque janelas seguras e isoladas; foque o dano letal em UM deles rapidamente para desequilibrar a balança e voltar à luta X1.',
        tag: 'Boss Strat',
      },
      {
        name: 'O Corte do Rabo de Kalameet (Obsidian Greatsword)',
        description: 'Mantenha distância média para baitar o Aerial Dive. Esquive do voo rasante de Kalameet, corra para ficar embaixo da base da cauda. Ele vai golpear o chão com o rabo reto, revelando uma janela de 2s para atacar. Uchigatana com buffs pesados corta rápido.',
        tag: 'Tail Cut Tech',
      },
      {
        name: 'Defesa Ignífuga e Estamina Perfeita',
        description: 'O Black Knight Shield com 95% de resistência a fogo é obrigatório. Sem ele, a baforada horizontal de Kalameet drena a estamina instantaneamente abrindo brechas para a morte.',
        tag: 'Survival Tech',
      },
    ],
    guideSections: [
      {
        id: 'sec-33-1',
        title: '1. O Desafio dos 2 Cachorros Elétricos',
        badge: 'Sanctuary Garden',
        items: [
          'Vá ao Local do Primeiro Chefe: Retorne para Oolacile Sanctuary e ande até a arena inicial.',
          'Equipamento: Eagle Shield, anéis leves, mobilidade e alto DPS explosivo.',
          'Sobrevivência: Mate o primeiro agressivamente.',
        ],
      },
      {
        id: 'sec-33-2',
        title: '2. O Arqueiro Cego e o Dragão',
        badge: 'Hawkeye Gough',
        items: [
          'Torre do Gough: Use a Crest Key na porta imensa na arena de Artorias.',
          'Diálogo do Dragão: Fale com Gough, confirme que Kalameet é um problema e solicite o tiro de arco colossal.',
          'Cutscene Épica: Assista Gough disparar às cegas, abatendo Kalameet para que ele possa lutar no chão.',
        ],
      },
      {
        id: 'sec-33-3',
        title: '3. Black Dragon Kalameet',
        badge: 'Kalameet',
        items: [
          'Preparo da Batalha: Fogueira para 20 Estus, Black Knight Shield e Uchigatana.',
          'Estratégia do Rabo: Mantenha distância média e force o Aerial Dive. Esquive e bata forte.',
          'Loot Pós-Batalha: Ao vencer, rode as cachoeiras da arena para pegar uma Titanite Slab extra.',
        ],
      },
    ],
    tasks: [
      {
        id: 'task-33-1',
        stageId: 'stage-33',
        title: 'Derrotar a dupla de Sanctuary Guardians',
        description: 'Opcional e brutal: elimine os dois guardiões alados na arena inicial.',
        category: 'boss',
        priority: 'optional',
        location: 'Sanctuary Garden',
        completed: false,
      },
      {
        id: 'task-33-2',
        stageId: 'stage-33',
        title: 'Destrancar a torre e pedir a ajuda de Hawkeye Gough',
        description: 'Assista a cena onde o gigante derruba Kalameet do céu.',
        category: 'npc',
        priority: 'essential',
        location: 'Torre após arena do Artorias',
        completed: false,
      },
      {
        id: 'task-33-3',
        stageId: 'stage-33',
        title: 'Cortar a cauda de Kalameet para obter a Obsidian Greatsword',
        description: 'Realize o bait no voo rasante e ataque o rabo quando afixado no chão.',
        category: 'weapon',
        priority: 'recommended',
        location: 'Vale de Kalameet',
        completed: false,
      },
      {
        id: 'task-33-4',
        stageId: 'stage-33',
        title: '⭐ Derrotar Black Dragon Kalameet e obter o Calamity Ring',
        description: 'Sobreviva às chamas abissais com o Black Knight Shield e elimine o dragão formidável.',
        category: 'boss',
        priority: 'essential',
        location: 'Vale de Kalameet',
        completed: false,
      },
      {
        id: 'task-33-5',
        stageId: 'stage-33',
        title: 'Coletar a Titanite Slab escondida na arena de Kalameet',
        description: 'Reviste os fundos da cachoeira na área do dragão após vencê-lo.',
        category: 'item',
        priority: 'essential',
        location: 'Vale de Kalameet',
        completed: false,
      },
    ],
  },

  // =========================================================================
  // STAGE 34 (Parte 34) - Troféus Armas Raras e Elementais
  // =========================================================================
  {
    id: 'stage-34',
    number: 34,
    title: 'Estágio 34: Troféus de Armas Raras e Elementais',
    subtitle: 'Maratona de Farm, Upgrades Massivos, Channeler\\'s Trident e Kiln of the First Flame',
    zone: 'Lordran Inteira & Ferreiros',
    recommendedDex: '40 DEX',
    recommendedPyroFlame: 'Estoque massivo de materiais',
    summary: 'Um episódio puramente utilitário com foco nas conquistas. Farm intenso de todas as variações de Titanite Chunks em New Londo, Crystal Cave, Lost Izalith e Tomb of the Giants. Coleta dos raríssimos Channeler\\'s Trident e armas dos Stone Giants. Aquisição de equipamentos com mercadores. Visita metódica aos quatro grandes ferreiros (Andre, Rickert, Vamos, Giant Blacksmith) forjando e ascendendo as armas a seus níveis máximos Elementais (Lightning, Crystal, Occult, Divine, Raw, Enchanted, Magic, Chaos e Normal +15), além de criar uma base de armas +10 vitais para o processo de Forja com Almas de Chefe no New Game+.',
    keyRewards: [
      'Troféu (Conquista): Lightning Weapon',
      'Troféu (Conquista): Crystal Weapon',
      'Troféu (Conquista): Occult Weapon',
      'Troféu (Conquista): Divine Weapon',
      'Troféu (Conquista): Raw Weapon',
      'Troféu (Conquista): Enchanted Weapon',
      'Troféu (Conquista): Magic Weapon',
      'Troféu (Conquista): Chaos Weapon',
      'Channeler\\'s Trident (Arma raríssima)',
      'Armas de Black Knight garantidas (Farm em Kiln)',
    ],
    levelRange: 'Lv. 94',
    buildStatus: {
      startLevel: 'Level 94',
      endLevel: 'Level 94',
      weapons: 'Diversas Armas Maximizadas',
      focusStat: 'Foco puro em materiais e souls farming',
      defense: 'Covetous Gold Serpent Ring + 10 Humanidades (Item Discovery 410 Máximo)',
    },
    combatTactics: [
      {
        name: 'Item Discovery Máximo (410)',
        description: 'Mantenha exatamente 10 humanidades "líquidas" no contador e equipe o Covetous Gold Serpent Ring ou Symbol of Avarice. Obrigatório para farm do Tridente de Magos.',
        tag: 'Farming Strat',
      },
      {
        name: 'Farm Eficiente de Chunks em Kiln',
        description: 'Abrir a porta da Kiln of the First Flame permite farmar Red, Blue, White e Normal Chunks nos cinco Black Knights, todos com 100% de drop rate, além das raras armas deles.',
        tag: 'Economic Tech',
      },
    ],
    guideSections: [
      {
        id: 'sec-34-1',
        title: '1. O Circuito dos Chunks Coloridos',
        badge: 'Farming',
        items: [
          'New Londo Ruins: 30 Titanite Chunks nos Darkwraiths e Slabs raras.',
          'Duke\\'s Archives / Caverna: 15 Blue Chunks nos Golems de Cristal (Use Fogo) e farmar os Magos pelo Channeler\\'s Trident.',
          'Lost Izalith: 15 Red Chunks matando Chaos Eaters (bocas no chão).',
          'Tomb of Giants: 15 White Chunks matando Pinwheels servos da água escura.',
        ],
      },
      {
        id: 'sec-34-2',
        title: '2. Lojas, Armas Base e Stone Giants',
        badge: 'Bottomless Box',
        items: [
          'Mercadores: Compre Bottomless Box e armas brancas cruas no Mercador de Undead Burg.',
          'Patches & Giant Blacksmith: Compre Crescent Axe (Patches) e Giant Halberd (Gigante).',
          'Darkroot Garden: Farme os Gigantes de Pedra (Stone Giants) antes da Borboleta para obter a Stone Greatsword e Greatshield.',
        ],
      },
      {
        id: 'sec-34-3',
        title: '3. O Ritual dos 4 Ferreiros',
        badge: 'Upgrades Max',
        items: [
          'Giant Blacksmith: Forje Lightning +5 e Crystal +5.',
          'Andre of Astora: Forje Occult +5, Divine +10, Raw +5 e todas as espadas base +10 para NG+.',
          'Rickert (New Londo): Forje Enchanted +5 e Magic +10.',
          'Vamos (Catacombs): Forje Chaos +5 (Fogo +10 faltou a red slab, reservado para NG+).',
        ],
      },
      {
        id: 'sec-34-4',
        title: '4. Kiln of the First Flame & Black Knights',
        badge: 'Lordvessel',
        items: [
          'Abertura: Ofereça as Almas no Firelink Altar.',
          'Farm Final: Mate os Black Knights para pegar Chunks garantidos e as armas raras (Sword, Greatsword, Halberd, Greataxe e Shield).',
        ],
      },
    ],
    tasks: [
      {
        id: 'task-34-1',
        stageId: 'stage-34',
        title: 'Farmar 30 Titanite Chunks regulares em New Londo',
        description: 'Equipe anel da cobra dourada e limpe as ruínas eliminando Darkwraiths.',
        category: 'item',
        priority: 'essential',
        location: 'New Londo Ruins',
        completed: false,
      },
      {
        id: 'task-34-2',
        stageId: 'stage-34',
        title: 'Drop Raro: Conseguir o Channeler\\'s Trident',
        description: 'Mate os feiticeiros dançarinos de Duke\\'s Archives até o item dropar.',
        category: 'weapon',
        priority: 'essential',
        location: 'Duke\\'s Archives',
        completed: false,
      },
      {
        id: 'task-34-3',
        stageId: 'stage-34',
        title: 'Drop Raro: Obter armas dos Stone Giants',
        description: 'Farme a Stone Greatsword e o Stone Greatshield em Darkroot Garden.',
        category: 'weapon',
        priority: 'essential',
        location: 'Darkroot Garden',
        completed: false,
      },
      {
        id: 'task-34-4',
        stageId: 'stage-34',
        title: 'Realizar upgrades máximos e desbloquear os 8 troféus elementais',
        description: 'Visite os 4 ferreiros para evoluir armas aos topos Lighting, Crystal, Occult, Divine, Raw, Enchanted, Magic e Chaos.',
        category: 'stat',
        priority: 'essential',
        location: 'Lordran (Todos os Ferreiros)',
        completed: false,
      },
      {
        id: 'task-34-5',
        stageId: 'stage-34',
        title: 'Abrir Kiln of the First Flame e farmar armas Black Knight',
        description: 'Ofereça as Lord Souls e mate os 5 cavaleiros negros pelo loot completo.',
        category: 'exploration',
        priority: 'essential',
        location: 'Kiln of the First Flame',
        completed: false,
      },
    ],
  },

  // =========================================================================
  // STAGE 35 (Parte 35) - Matando NPCs e Lord Gwyn
  // =========================================================================
  {
    id: 'stage-35',
    number: 35,
    title: 'Estágio 35: A Limpa de NPCs e Batalha Final contra Gwyn',
    subtitle: 'Últimas Trocas no Snuggly, Chacina Pessoal e Final The Dark Lord',
    zone: 'Lordran (NPCs), Painted World (Farm) & Kiln of the First Flame',
    recommendedDex: '40 DEX',
    recommendedPyroFlame: 'Dark Silver Tracer & Gold Tracer upadas com Twinkling Titanites',
    summary: 'Os momentos finais do New Game! Troca-se a Alma de Manus pelo feitiço "Pursuers" com o corvo Snuggly, e musgos por Twinkling Titanites. A famigerada "Limpa": assassinar implacavelmente quase todos os NPCs e mercadores amigáveis pelo mundo para absorver suas almas, Humanidades Duplas, sets e armas únicas, deixando Lordran sem vida. Uso do Painted World para acúmulo extremo de almas para compra de sets de chefões com Domhnall of Zena. Por fim, uma batalha formidável onde Solaire of Astora auxilia na distração de Lord Gwyn para aniquilação a base de puro dano piromântico nas costas. O abandono da Primeira Chama concretiza o Final Dark Lord, dando início à transição direta para o New Game+.',
    keyRewards: [
      'Feitiço Pursuers (Troca por Manus Soul)',
      'Blacksmith Hammer & Blacksmith Great Hammer & Hammer of Vamos (Matando Ferreiros)',
      'Crescent Axe (Matando Patches) e Uchigatana (Matando Undead Merchant)',
      'Black Knight Set completo em Kiln',
      'Soul of Gwyn, Lord of Cinder',
      'Final The Dark Lord',
    ],
    levelRange: 'Lv. 94',
    buildStatus: {
      startLevel: 'Level 94',
      endLevel: 'Level 94+',
      weapons: 'Dark Silver Tracer / Gold Tracer / Balder Side Sword +15',
      focusStat: 'Todas as Piromâncias Base (exceto Toxic Mist), Todos Feitiços Base e Milagres Preparados.',
      defense: 'Black Knight Shield (Defesa imbatível contra o fogo de Gwyn) + Black Knight Set',
    },
    combatTactics: [
      {
        name: 'Gwyn Pyro Cheese com Solaire',
        description: 'Invoque Solaire para receber o furioso combo inicial de Gwyn. Pelas costas de Gwyn, despeje Great Chaos Fireball e Great Combustion repetidamente. O dano brutal terminará a luta antes de Solaire perecer.',
        tag: 'Boss Strat',
      },
      {
        name: 'O Farm Furtivo de Ariamis',
        description: 'Roteie do bonfire de Painted World até a praça dos Phalanxes. Utilize feitiços amplos como Fire Tempest ou Chaos Storm no centro da falange, retorne a fogueira e repita, ganhando milhares de almas em minutos.',
        tag: 'Farming Strat',
      },
    ],
    guideSections: [
      {
        id: 'sec-35-1',
        title: '1. O Ninho de Snuggly',
        badge: 'Snuggly',
        items: [
          'Trocas: Retorne ao Undead Asylum, deixe a Soul of Manus e dê Quit/Load para pegar Pursuers.',
          'Musgos por Cintilantes: Troque os Moss Clumps verdes e roxos venenosos por Twinkling Titanites e evolua suas lâminas (Tracers).',
        ],
      },
      {
        id: 'sec-35-2',
        title: '2. Assassinato em Massa (Pré-NG+)',
        badge: 'NPC Kill',
        items: [
          'Aviso: Faça isso SÓ antes do boss final.',
          'Alvos Principais: Undead Merchant, Andre, Oswald, Giant Blacksmith, Vamos, Patches, Elizabeth, Chester, Reah e Gwyndolin (se não fez).',
          'Sets dos Chefes: Acumule almas, compre os sets caros do Domhnall de Zena (Aqueduto) e mate-o no final.',
        ],
      },
      {
        id: 'sec-35-3',
        title: '3. A Batalha contra Gwyn, Lord of Cinder',
        badge: 'Gwyn',
        items: [
          'Coleta em Kiln: Pegue a armadura dos Black Knights numa viga da longa passarela de cinzas.',
          'A Luta: Invoque Solaire, equipe o Black Knight Shield, e derreta o Rei Caído com fogo e armas rápidas.',
          'O Final: NÃO ACENDA A FOGUEIRA, dê as costas à chama, saia pela porta para ativar a cutscene The Dark Lord e entrar em New Game+.',
        ],
      },
    ],
    tasks: [
      {
        id: 'task-35-1',
        stageId: 'stage-35',
        title: 'Trocar a Alma de Manus pelo feitiço Pursuers no ninho do corvo',
        description: 'Viaje ao asilo e use o método Quit/Load com o Snuggly.',
        category: 'item',
        priority: 'recommended',
        location: 'Northern Undead Asylum',
        completed: false,
      },
      {
        id: 'task-35-2',
        stageId: 'stage-35',
        title: 'Matar os 4 Ferreiros para obter os martelos raros',
        description: 'Sacrifique Andre, Giant, Rickert (sem loot) e Vamos para coletar armas e almas únicas (Faça somente no fim!).',
        category: 'npc',
        priority: 'essential',
        location: 'Lordran',
        completed: false,
      },
      {
        id: 'task-35-3',
        stageId: 'stage-35',
        title: 'Comprar os Sets de armadura dos Bosses com Domhnall e abatê-lo',
        description: 'Farme almas no Painted World e compre as armaduras brilhantes de Ornstein, Artorias, etc.',
        category: 'exploration',
        priority: 'recommended',
        location: 'Aqueduto (Firelink) e Painted World',
        completed: false,
      },
      {
        id: 'task-35-4',
        stageId: 'stage-35',
        title: 'Coletar o Black Knight Set completo na passarela',
        description: 'Ande pelas vigas finas de cinzas na fenda antes da arena de Gwyn.',
        category: 'item',
        priority: 'essential',
        location: 'Kiln of the First Flame',
        completed: false,
      },
      {
        id: 'task-35-5',
        stageId: 'stage-35',
        title: '⭐ Derrotar Gwyn, Lord of Cinder (Com Solaire)',
        description: 'Use magias de Pyro nas costas do chefe enquanto Solaire toma a frente, ou treine seus parries perfeitos.',
        category: 'boss',
        priority: 'essential',
        location: 'Kiln of the First Flame',
        completed: false,
      },
      {
        id: 'task-35-6',
        stageId: 'stage-35',
        title: 'Ativar o Final "The Dark Lord" (Sair sem acender a Chama)',
        description: 'Apenas deixe a arena para trás e inicie a jornada do NG+.',
        category: 'exploration',
        priority: 'essential',
        location: 'Arena de Gwyn',
        completed: false,
      },
    ],
  },

  // =========================================================================
  // STAGE 36 (Parte 36) - Magias, Armas dos Chefões e Platina
  // =========================================================================
  {
    id: 'stage-36',
    number: 36,
    title: 'Estágio 36: Magias, Armas dos Chefões e Platina 100%',
    subtitle: 'Rotas de New Game+ e New Game++, Troféus de Magias Mágicas, e Knight\\'s Honor',
    zone: 'Lordran (NG+ / NG++)',
    recommendedDex: '40 DEX',
    recommendedPyroFlame: 'Todo o arsenal massivo a disposição.',
    summary: 'A gloriosa volta por cima em NG+ para finalizar a platina! Criação final do milagre Sunlight Spear com a Alma de Gwyn no Sunlight Altar. Adoecimento e compra da última piromancia, Toxic Mist. Avanço rápido derrotando Quelaag, Bell Gargoyles, Iron Golem, O&S (Derrotando Ornstein primeiro) e uma nova derrota de Gwyndolin e Priscilla. Ascensão em Anor Londo de mais de uma dúzia de armas de chefes fundindo almas pesadas e armas +10 para construir Greatsword of Artorias, Chaos Blade, Smough\\'s Hammer e Dragonslayer Spear. E a temida e necessária terceira volta (NG++) aos aposentos de Sif para pegar sua terceira alma vital para selar o troféu de Armas Raras: Knight\\'s Honor.',
    keyRewards: [
      'Troféu (Conquista): Prayer of a Maiden (Todos os Milagres)',
      'Troféu (Conquista): Bond of a Pyromancer (Todas Piromâncias)',
      'Troféu (Conquista): Fire Weapon (Max Red Slab)',
      'Troféu (Conquista): Knight\\'s Honor (Todas as Armas Raras - PLATINA!)',
      'Troféu de Ouro: The Dark Soul',
    ],
    levelRange: 'Lv. 100+',
    buildStatus: {
      startLevel: 'Level 100+',
      endLevel: 'Level Platina',
      weapons: 'Artorias Greatsword, Tracers, Chaos Blade, Q. Furysword.',
      focusStat: 'Masterização de Atributos Secundários',
      defense: 'A sua melhor build focada ou puro fashion souls.',
    },
    combatTactics: [
      {
        name: 'Rapidez no NG+ e NG++',
        description: 'No NG+, você é muito forte desde o início, mas os inimigos batem de forma brutal. Não perca tempo enfrentando inimigos de fase comuns, corra direto para os Chefes e Fogueiras necessárias.',
        tag: 'Speedrun Strat',
      },
      {
        name: 'Alma do Sif',
        description: 'Sif é a única alma de boss que possui TRÊS criações (Artorias Greatsword True, Cursed e o Shield). Logo, alcançar Anor Londo no New Game++ é inevitável para a Platina.',
        tag: 'Trophy Tech',
      },
    ],
    guideSections: [
      {
        id: 'sec-36-1',
        title: '1. O Fim da Magia',
        badge: 'NG+',
        items: [
          'Milagre de Gwyn: Logo após o Taurus Demon, passe pelo dragão e ore no Sunlight Altar (pacto) para trocar a Gwyn Soul por Sunlight Spear. (Conquista: Todos os Milagres)',
          'Piromancia em Blighttown: Vá à sala da irmã da Quelaag, seja infectado pelo portador de ovo nas costas de Eingyi e compre Toxic Mist. (Conquista: Todas as Piromâncias)',
          'Fogo +10: Se pegou a Red Slab de Lost Izalith, evolua a Fire Spear ou Scimitar no Vamos para o troféu.',
        ],
      },
      {
        id: 'sec-36-2',
        title: '2. A Coleta Brutal de Almas (NG+)',
        badge: 'Boss Run',
        items: [
          'Refazer Chefes Finais: Derrote Sif, Moonlight Butterfly, Quelaag, Iron Golem, Gwyndolin, Priscilla.',
          'Ornstein & Smough V2: Desta vez, DEIXE o gigante Smough para a 2ª fase e mate Ornstein primeiro para conseguir a Soul of Smough.',
        ],
      },
      {
        id: 'sec-36-3',
        title: '3. A Forja e o NG++',
        badge: 'Knight\'s Honor',
        items: [
          'Giant Blacksmith: Forje 14 armas base +10 em Armas de Chefes (Smough\'s Hammer, Golem Axe, Chaos Blade, Lifehunt Scythe, etc).',
          'Sif 3ª Morte: Complete o NG+, avance pelo Asylum e chegue em Darkroot Garden no NG++ o mais rápido possível para matar Sif a terceira e última vez.',
          'O Troféu de Ouro: Entregue a 3ª Alma do Sif ao Giant Blacksmith de Anor Londo (NG++), forje o item que faltava e observe o selo glorioso da Platina "The Dark Soul" pipocar na tela!',
        ],
      },
    ],
    tasks: [
      {
        id: 'task-36-1',
        stageId: 'stage-36',
        title: 'Trocar Alma de Gwyn por Sunlight Spear (Conquista de Milagres)',
        description: 'Vá ao Sunlight Altar (atrás do dragão vermelho) no NG+.',
        category: 'stat',
        priority: 'essential',
        location: 'Undead Parish (Altar do Sol)',
        completed: false,
      },
      {
        id: 'task-36-2',
        stageId: 'stage-36',
        title: 'Comprar a piromancia Toxic Mist (Conquista de Piromâncias)',
        description: 'Pegue o parasita de ovos na cabeça em Blighttown e compre com Eingyi.',
        category: 'item',
        priority: 'essential',
        location: 'Quelaag\'s Domain',
        completed: false,
      },
      {
        id: 'task-36-3',
        stageId: 'stage-36',
        title: 'Evoluir arma de Fogo para +10 (Conquista de Arma de Fogo)',
        description: 'Use a Red Titanite Slab de Lost Izalith no Vamos das Catacumbas.',
        category: 'weapon',
        priority: 'essential',
        location: 'Catacombs',
        completed: false,
      },
      {
        id: 'task-36-4',
        stageId: 'stage-36',
        title: 'Realizar NG+ Boss Rush (Pegar segundas almas requeridas)',
        description: 'Derrote Gwyndolin, Sif, Priscilla, Moonlight Butterfly e Smough na fase super.',
        category: 'boss',
        priority: 'essential',
        location: 'Lordran NG+',
        completed: false,
      },
      {
        id: 'task-36-5',
        stageId: 'stage-36',
        title: 'Forjar mais de 10 armas de Chefões com o Giant Blacksmith',
        description: 'Combine as armas +10 base com as Souls do NG+ em Anor Londo.',
        category: 'weapon',
        priority: 'essential',
        location: 'Anor Londo (Ferreiro Gigante)',
        completed: false,
      },
      {
        id: 'task-36-6',
        stageId: 'stage-36',
        title: '⭐ Chegar no NG++, obter a 3ª Alma do Sif e PLATINAR',
        description: 'Derrote o lobo gigante pela terceira vez e forje a última arma rara de Artorias para desbloquear "The Dark Soul".',
        category: 'exploration',
        priority: 'essential',
        location: 'Darkroot Garden (NG++) & Anor Londo',
        completed: false,
      },
    ],
  },
];
`;

const updatedContent = content.replace(
  /    \],\n  },\n\];/g,
  `    ],\n  },\n${newStages}`
);

fs.writeFileSync('src/data/roadguideStagesPart3.ts', updatedContent);
console.log('Stages successfully appended.');
